version: '3.8'  # Puedes ajustar la versión según la que desees usar

services:
  redis:
    container_name: smart-shell-redis
    env_file:
      - ./.env
    image: redis/redis-stack
    ports:
      - "6379:6379"
    networks:
      - smart-shell-net  # Conexión a la red smart-shell-net
    command: redis-server --requirepass $REDIS_PASSWORD --maxmemory 1gb --maxmemory-policy volatile-lru

networks:
  smart-shell-net:  # Definición de la red smart-shell-net
    external: true   # Indicador de que la red ya está creada externamente