services:
  app:
    container_name: smart-shell-redis
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      SMART_SHELL_REDIS_PASSWORD: ${SMART_SHELL_REDIS_PASSWORD}
    ports:
      - "${SMART_SHELL_REDIS_PORT}:6379"
    networks:
      - smart-shell-net
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${SMART_SHELL_REDIS_PASSWORD}
    restart: unless-stopped

networks:
  smart-shell-net:
    external: true