services:
  app:
    container_name: smart-shell-redis
    env_file:
      - ./.env
    image: redis/redis-stack
    ports:
      - "${SMART_SHELL_REDIS_PORT}:6379"
    networks:
      - smart-shell-net
    command: redis-server --port 6379 --bind 0.0.0.0 --requirepass $SMART_SHELL_REDIS_PASSWORD --maxmemory 1gb --maxmemory-policy volatile-lru
    restart: unless-stopped

networks:
  smart-shell-net:
    external: true