apiVersion: v1
kind: Service
metadata:
  name: redis-external-service
  namespace: smart-shell-production
  annotations:
    metallb.universe.tf/allow-shared-ip: "192.168.100.241"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.241
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis